# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1768ddb3a40b62ba64d555ede4b9a4a5f25d7486d302e3900d5e9026b21a814b03b7e8ee40e06f1e4c14161fa92a40e75911aca78d726655ae3a2ae3718430a8

test:
  secret_key_base: d00c89f1c86a0b5417b57188bc17a54d4ba96f085524dcfb579395aa232467c0b77b22e8412789b66d1c9e27961f89577816679d85c959b1f44741e7537b64f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
